# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

mermaid = Word.create(name: "mermaid")
mermaid.valid_words.create([{ name: "admire" }, { name: "dammer" }, { name: "dimmer" }, 
{ name: "maimed" }, { name: "maimer" }, { name: "rammed" }, { name: "rimmed" },  
{ name: "rimmed" }, { name: "aider" }, { name: "aimed" }, { name: "aimer" }, 
{ name: "aired" }, { name: "amide" }, { name: "armed" }, { name: "damme" }, 
{ name: "deair" }, { name: "derma" }, { name: "dimer" }, { name: "diram" }, 
{ name: "dream" }, { name: "irade" }, { name: "madre" }, { name: "maire" }, 
{ name: "mamie" }, { name: "marid" }, { name: "marid" }, { name: "media" }, 
{ name: "mimed" }, { name: "mimer" }, { name: "mired" }, { name: "ramie" }, 
{ name: "redia" }, { name: "rimae" }, { name: "rimed" }, { name: "aide" }, 
{ name: "amid" }, { name: "amie" }, { name: "amir" }, { name: "ared" }, { name: "arid" },
{ name: "dame" }, { name: "dare" }, { name: "dari" }, { name: "dear" }, { name: "derm" },
{ name: "dime" }, { name: "dire" }, { name: "dram" }, { name: "eard" }, { name: "emir" },
{ name: "emma" }, { name: "idea" }, { name: "idem" }, { name: "imam" }, { name: "ired" },
{ name: "made" }, { name: "maid" }, { name: "maim" }, { name: "mair" }, { name: "mard" },
{ name: "mare" }, { name: "marm" }, { name: "mead" }, { name: "meri" }, { name: "mime" },
{ name: "mire" }, { name: "rade" }, { name: "raid" }, { name: "rami" }, { name: "read" },
{ name: "ream" }, { name: "riad" }, { name: "ride" }, { name: "riem" }, { name: "rima" }, 
{ name: "rime" }])

crooked = Word.create(name: "crooked")
crooked.valid_words.create([{ name: "cooked" }, { name: "cooker" }, { name: "corked" }, 
{ name: "docker" }, { name: "recook" }, { name: "redock" }, { name: "rocked" }, 
{ name: "rooked" }, { name: "coder" }, { name: "coked" }, { name: "cooed" }, 
{ name: "cooer" }, { name: "cored" }, { name: "credo" }, { name: "crook" }, 
{ name: "decko" }, { name: "decor" }, { name: "dooce" }, { name: "dreck" }, 
{ name: "drook" }, { name: "ocker" }, { name: "rodeo" }, { name: "roked" },
{ name: "cero" }, { name: "code" }, { name: "coed" }, { name: "coke" }, { name: "cook" },
{ name: "cord" }, { name: "core" }, { name: "cork" }, { name: "cred" }, { name: "deck" },
{ name: "deco" }, { name: "dero" }, { name: "dock" }, { name: "doco" }, { name: "doek" },
{ name: "doer" }, { name: "dook" }, { name: "door" }, { name: "dore" }, { name: "dork" },
{ name: "drek" }, { name: "ecod" }, { name: "kero" }, { name: "kore" }, { name: "koro" },
{ name: "odor" }, { name: "ordo" }, { name: "reck" }, { name: "redo" }, { name: "rock" },
{ name: "rode" }, { name: "roed" }, { name: "roke" }, { name: "rood" }, { name: "rook" }]) 

witches = Word.create(name: "witches")
witches.valid_words.create([{ name: "ethics" }, { name: "itches" }, { name: "switch" }, 
{ name: "swithe" }, { name: "theics" }, { name: "tiches" }, { name: "wechts" }, { name: "whites" }, 
{ name: "wiches" }, { name: "withes" }, { name: "cesti" }, { name: "chest" }, { name: "chews" },
{ name: "chits" }, { name: "cites" }, { name: "ethic" }, { name: "heist" }, { name: "iches" }, 
{ name: "shite" }, { name: "sicht" }, { name: "sieth" }, { name: "sithe" }, { name: "stich" }, 
{ name: "swith" }, { name: "techs" }, { name: "theic" }, { name: "thews" }, { name: "tices" }, 
{ name: "twice" }, { name: "wecht" }, { name: "whets" }, { name: "whist" }, { name: "white" }, 
{ name: "whits" }, { name: "wisht" }, { name: "witch" }, { name: "wites" }, { name: "withe" }, 
{ name: "withs" }, { name: "chew" }, { name: "chis" }, { name: "chit" }, { name: "cist" }, 
{ name: "cite" }, { name: "cits" }, { name: "echt" }, { name: "eish" }, { name: "etch" }, 
{ name: "eths" }, { name: "etic" }, { name: "ewts" }, { name: "hest" }, { name: "hets" }, 
{ name: "hews" }, { name: "hies" }, { name: "hist" }, { name: "hits" }, { name: "ices" }, 
{ name: "ichs" }, { name: "itch" }, { name: "sech" }, { name: "sect" }, { name: "shet" }, 
{ name: "shew" }, { name: "sice" }, { name: "sich" }, { name: "site" }, { name: "sith" }, 
{ name: "stew" }, { name: "stie" }, { name: "tech" }, { name: "tecs" }, { name: "tews" }, 
{ name: "thew" }, { name: "this" }, { name: "tice" }, { name: "tich" }, { name: "tics" }, 
{ name: "ties" }, { name: "west" }, { name: "wets" }, { name: "whet" }, { name: "whit" }, 
{ name: "wice" }, { name: "wich" }, { name: "wise" }, { name: "wish" }, { name: "wist" },
{ name: "wite" }, { name: "with" }, { name: "wits" }])

cheddar = Word.create(name: "cheddar")
cheddar.valid_words.create([{ name: "arched" }, { name: "carded" }, { name: "chared" }, 
{ name: "echard" }, { name: "ached" }, { name: "acred" }, { name: "adder" }, { name: "adred" }, 
{ name: "arced" }, { name: "aredd" }, { name: "cadre" }, { name: "cared" }, { name: "cedar" }, 
{ name: "chard" }, { name: "chare" }, { name: "dared" }, { name: "decad" }, { name: "dread" }, 
{ name: "haded" }, { name: "hared" }, { name: "heard" }, { name: "raced" }, { name: "rache" }, 
{ name: "rahed" }, { name: "reach" }, { name: "readd" }, { name: "aced" }, { name: "acer" }, 
{ name: "ache" }, { name: "acre" }, { name: "ahed" }, { name: "arch" }, { name: "ared" }, 
{ name: "cade" }, { name: "card" }, { name: "care" }, { name: "chad" }, { name: "char" }, 
{ name: "cher" }, { name: "cred" }, { name: "dace" }, { name: "dare" }, { name: "dead" }, 
{ name: "dear" }, { name: "drac" }, { name: "drad" }, { name: "each" }, { name: "eard" }, 
{ name: "ecad" }, { name: "hade" }, { name: "haed" }, { name: "hard" }, { name: "hare" }, 
{ name: "head" }, { name: "hear" }, { name: "herd" }, { name: "race" }, { name: "rach" }, 
{ name: "rade" }, { name: "read" }, { name: "redd" }, { name: "rhea" }])

gesture = Word.create(name: "gesture")
gesture.valid_words.create([{ name: "egrets" }, { name: "greets" }, { name: "gutser" }, 
{ name: "regest" }, { name: "retuse" }, { name: "egers" }, { name: "egest" }, 
{ name: "egret" }, { name: "ester" }, { name: "geest" }, { name: "geres" }, { name: "geste" }, 
{ name: "grees" }, { name: "greet" }, { name: "grese" }, { name: "grues" }, { name: "guest" }, 
{ name: "reest" }, { name: "reges" }, { name: "reset" }, { name: "reuse" }, { name: "segue" }, 
{ name: "serge" }, { name: "steer" }, { name: "stere" }, { name: "sture" }, { name: "surge" }, 
{ name: "teers" }, { name: "tegus" }, { name: "teres" }, { name: "terse" }, { name: "trees" },  
{ name: "trues" }, { name: "trugs" }, { name: "urges" }, { name: "eger" }, { name: "eres" }, 
{ name: "ergs" }, { name: "erst" }, { name: "euge" }, { name: "gees" }, { name: "gere" }, 
{ name: "gers" }, { name: "gert" }, { name: "gest" }, { name: "gets" }, { name: "gree" }, 
{ name: "gues" }, { name: "gurs" }, { name: "gust" }, { name: "guts" }, { name: "rees" }, 
{ name: "regs" }, { name: "rest" }, { name: "rete" }, { name: "rets" }, { name: "rues" }, 
{ name: "rugs" }, { name: "ruse" }, { name: "rust" }, { name: "ruts" },  { name: "seer" }, 
{ name: "sere" }, { name: "suer" }, { name: "suet" }, { name: "sure" }, { name: "teer" }, 
{ name: "tees" }, { name: "tegs" }, { name: "tegu" }, { name: "tree" }, { name: "tres" }, 
{ name: "true" }, { name: "trug" }, { name: "tugs" }, { name: "ures" }, { name: "urge" }, 
{ name: "user" }, { name: "utes" }])

granola = Word.create(name: "granola")
granola.valid_words.create([{ name: "agonal" }, { name: "analog" }, { name: "angola" }, 
{ name: "angora" }, { name: "langar" }, { name: "organa" }, { name: "raglan" }, 
{ name: "agora" }, { name: "alang" }, { name: "algor" }, { name: "along" }, { name: "anglo" }, 
{ name: "argal" }, { name: "argan" }, { name: "argol" }, { name: "argon" }, { name: "gnarl" }, 
{ name: "goral" }, { name: "graal" }, { name: "grana" }, { name: "groan" }, { name: "lagan" }, 
{ name: "largo" }, { name: "logan" }, { name: "longa" }, { name: "loran" }, { name: "nagor" }, 
{ name: "orang" }, { name: "organ" }, { name: "ranga" }, { name: "rolag" }, { name: "agar" }, 
{ name: "agon" }, { name: "alan" }, { name: "alar" }, { name: "alga" }, { name: "anga" }, 
{ name: "anoa" }, { name: "arna" }, { name: "gala" }, { name: "gaol" }, { name: "gnar" }, 
{ name: "goal" }, { name: "gora" }, { name: "gran" }, { name: "lana" }, { name: "lang" }, 
{ name: "larn" }, { name: "loan" }, { name: "long" }, { name: "lorn" }, { name: "naga" }, 
{ name: "nala" }, { name: "oral" }, { name: "raga" }, { name: "rana" }, { name: "rang" }, 
{ name: "roan" }, { name: "rong" }])

costume = Word.create(name: "costume")
costume.valid_words.create([{ name: "comets" }, { name: "comtes" }, { name: "custom" }, 
{ name: "mucose" }, { name: "comes" }, { name: "comet" }, { name: "comte" }, { name: "comus" }, 
{ name: "coset" }, { name: "coste" }, { name: "cotes" }, { name: "cutes" }, { name: "escot" }, 
{ name: "estoc" }, { name: "meous" }, { name: "mesto" }, { name: "moste" }, { name: "motes" }, 
{ name: "motus" }, { name: "moues" }, { name: "mouse" }, { name: "moust" }, { name: "muset" }, 
{ name: "mutes" }, { name: "scout" }, { name: "scute" }, { name: "smote" }, { name: "smout" }, 
{ name: "souce" }, { name: "souct" }, { name: "tomes" }, { name: "touse" }, { name: "come" }, 
{ name: "coms" }, { name: "cose" }, { name: "cost" }, { name: "cote" }, { name: "cots" }, 
{ name: "cues" }, { name: "cute" }, { name: "cuts" }, { name: "ecos" }, { name: "ecus" }, 
{ name: "emos" }, { name: "emus" }, { name: "meou" }, { name: "mets" }, { name: "meus" }, 
{ name: "mocs" }, { name: "moes" }, { name: "mose" }, { name: "most" }, { name: "mote" }, 
{ name: "mots" }, { name: "motu" }, { name: "moue" }, { name: "mous" }, { name: "muse" }, 
{ name: "muso" }, { name: "must" }, { name: "mute" }, { name: "muts" }, { name: "oust" }, 
{ name: "outs" }, { name: "scot" }, { name: "scum" }, { name: "scut" }, { name: "seco" }, 
{ name: "sect" }, { name: "smut" }, { name: "some" }, { name: "soum" }, { name: "sout" }, 
{ name: "stem" }, { name: "stum" }, { name: "suet" }, { name: "sumo" }, { name: "tecs" }, 
{ name: "tems" }, { name: "tocs" }, { name: "toes" }, { name: "tome" }, { name: "toms" }, 
{ name: "tose" }, { name: "tums" }, { name: "utes" }])

breathe = Word.create(name: "breathe")
breathe.valid_words.create([{ name: "aether" }, { name: "bather" }, { name: "beater" }, 
{ name: "berate" }, { name: "bertha" }, { name: "berthe" }, { name: "breath" }, 
{ name: "heater" }, { name: "hereat" }, { name: "rebate" }, { name: "reheat" }, 
{ name: "arete" }, { name: "bathe" }, { name: "beare" }, { name: "beath" }, { name: "beret" }, 
{ name: "berth" }, { name: "earth" }, { name: "eater" }, { name: "eathe" }, { name: "ether" }, 
{ name: "hater" }, { name: "heare" }, { name: "heart" }, { name: "rathe" }, { name: "reate" }, 
{ name: "rehab" }, { name: "taber" }, { name: "thebe" }, { name: "there" }, { name: "thrae" }, 
{ name: "three" }, { name: "abet" }, { name: "aret" }, { name: "baht" }, { name: "bare" }, 
{ name: "bate" }, { name: "bath" }, { name: "bear" }, { name: "beat" }, { name: "beer" }, 
{ name: "beet" }, { name: "bere" }, { name: "beta" }, { name: "bete" }, { name: "beth" }, 
{ name: "bhat" }, { name: "brae" }, { name: "brat" }, { name: "bree" }, { name: "eath" }, 
{ name: "ethe" }, { name: "haet" }, { name: "hare" }, { name: "hart" }, { name: "hate" }, 
{ name: "hear" }, { name: "heat" }, { name: "herb" }, { name: "here" }, { name: "hete" }, 
{ name: "rate" }, { name: "rath" }, { name: "rete" }, { name: "rhea" }, { name: "tahr" }, 
{ name: "tare" }, { name: "tear" }, { name: "teer" }, { name: "tehr" }, { name: "thae" }, 
{ name: "thar" }, { name: "thee" }, { name: "tree" }])

crystal = Word.create(name: "crystal")
crystal.valid_words.create([{ name: "clarts" }, { name: "clarty" }, { name: "lycras" }, 
{ name: "stylar" }, { name: "acyls" }, { name: "artsy" }, { name: "aryls" }, { name: "carls" }, 
{ name: "carts" }, { name: "clart" }, { name: "clary" }, { name: "clast" }, { name: "clats" }, 
{ name: "clays" }, { name: "crays" }, { name: "lyart" }, { name: "lycra" }, { name: "ryals" }, 
{ name: "salty" }, { name: "satyr" }, { name: "scaly" }, { name: "scart" }, { name: "scary" }, 
{ name: "scrat" }, { name: "scray" }, { name: "slart" }, { name: "slaty" }, { name: "stray" }, 
{ name: "talcs" }, { name: "talcy" }, { name: "trays" }, { name: "acts" }, { name: "acyl" }, 
{ name: "alts" }, { name: "arcs" }, { name: "arsy" }, { name: "arts" }, { name: "arty" }, 
{ name: "aryl" }, { name: "carl" }, { name: "cars" }, { name: "cart" }, { name: "cast" }, 
{ name: "cats" }, { name: "cays" }, { name: "clat" }, { name: "clay" }, { name: "cray" }, 
{ name: "cyst" }, { name: "lacs" }, { name: "lacy" }, { name: "lars" }, { name: "last" }, 
{ name: "lats" }, { name: "lays" }, { name: "lyra" }, { name: "racy" }, { name: "rast" }, 
{ name: "rats" }, { name: "rays" }, { name: "ryal" }, { name: "ryas" }, { name: "salt" }, 
{ name: "scar" }, { name: "scat" }, { name: "scry" }, { name: "slat" }, { name: "slay" }, 
{ name: "star" }, { name: "stay" }, { name: "talc" }, { name: "tars" }, { name: "tays" }, 
{ name: "tray" }, { name: "tsar" }])

neutral = Word.create(name: "neutral")
neutral.valid_words.create([{ name: "altern" }, { name: "antler" }, { name: "aunter" }, 
{ name: "eluant" }, { name: "learnt" }, { name: "lunate" }, { name: "nature" }, 
{ name: "neural" }, { name: "rental" }, { name: "runlet" }, { name: "ternal" }, 
{ name: "ulnare" }, { name: "unreal" }, { name: "alert" }, { name: "alter" }, 
{ name: "alure" }, { name: "antre" }, { name: "arnut" }, { name: "artel" },
{ name: "laten" }, { name: "later" }, { name: "leant" }, { name: "learn" }, { name: "lunar" }, 
{ name: "lunet" }, { name: "lutea" }, { name: "luter" }, { name: "neral" }, { name: "ratel" }, 
{ name: "renal" }, { name: "taler" }, { name: "tuner" }, { name: "ulnae" }, { name: "ulnar" }, 
{ name: "ultra" }, { name: "unlet" }, { name: "urate" }, { name: "ureal" }, { name: "urena" }, 
{ name: "urent" }, { name: "urnal" }, { name: "ante" }, { name: "aret" }, { name: "arle" }, 
{ name: "aune" }, { name: "aunt" }, { name: "earl" }, { name: "earn" }, { name: "elan" }, 
{ name: "etna" }, { name: "laer" }, { name: "lane" }, { name: "lant" }, { name: "lare" }, 
{ name: "larn" }, { name: "late" }, { name: "latu" }, { name: "lean" }, { name: "lear" }, 
{ name: "leat" }, { name: "lent" }, { name: "luna" }, { name: "lune" }, { name: "lunt" }, 
{ name: "lure" }, { name: "lute" }, { name: "nare" }, { name: "neal" }, { name: "near" }, 
{ name: "neat" }, { name: "nurl" }, { name: "rale" }, { name: "rant" }, { name: "rate" }, 
{ name: "ratu" }, { name: "raun" }, { name: "real" }, { name: "rean" }, { name: "rent" }, 
{ name: "rule" }, { name: "rune" }, { name: "runt" }, { name: "tael" }, { name: "tale" }, 
{ name: "tane" }, { name: "tare" }, { name: "tarn" }, { name: "teal" }, { name: "tear" }, 
{ name: "tela" }, { name: "tern" }, { name: "true" }, { name: "tuan" }, { name: "tule" }, 
{ name: "tuna" }, { name: "tune" }, { name: "turn" }, { name: "ulan" }, { name: "ulna" }, 
{ name: "urea" }])